#!/bin/bash

set -o errexit

set -o xtrace

HOST=$(head -n1 $1 | awk '{ print $2}')
CUSTOM_URL="http://$HOST:8090"

if [ ! -d tests ]; then
  echo 'no tests specifications found'
  exit 0
fi

pushd ./tests

rainforest validate --token $RAINFOREST_TOKEN
rainforest upload --token $RAINFOREST_TOKEN
rainforest run \
           --token $RAINFOREST_TOKEN \
           --tag automated \
           --custom-url $CUSTOM_URL \
           --description "wercker build for ${WERCKER_GIT_COMMIT:0:8}" \
           > /tmp/RAINFOREST.run

RESULT_LINE=$(tail -n1 RAINFOREST.run | grep 'Issued run')

[ -n "$RESULT_LINE" ] && \
  echo $RESULT_LINE | awk '{print $NF}' > RAINFOREST.run_id
