#!/bin/bash

set -o errexit

HOST=$(ec2metadata | grep public-ipv4 | FS=':' awk '{print $2}')

export HOME=/root/
export REPOSITORY_PATH='/opt/koding'

export CI="true"
export WERCKER="true"

export CONFIG_DEBUGMODE="true"

ulimit -n 10240

cd $REPOSITORY_PATH

git config user.email 'sysops@koding.com'
git config user.name 'Koding Bot'

npm install --unsafe-perm
./configure --config dev --host $HOST:8090 --disable-segment
go/build.sh
make -C client dist

./run services

sleep 60 # let dockers boot up

./run migrate up

./run exec supervisord -c $REPOSITORY_PATH/supervisord.conf

exit 0
