#!/bin/bash

set -o errexit

HOSTNAME="`ec2metadata --instance-id`.test.ci.koding.io"

export HOME=/root/
export REPOSITORY_PATH='/opt/koding'

export CI="true"
export WERCKER="true"

export CONFIG_DEBUGMODE="true"

ulimit -n 10240

cd $REPOSITORY_PATH

git config user.email 'sysops@koding.com'
git config user.name 'Koding Bot'

npm install --unsafe-perm
./configure --config dev --host $HOSTNAME:8090 --hostname $HOSTNAME --publicPort 8090 --disable-segment
go/build.sh
make -C client dist

./run services

sleep 60 # let dockers boot up

./run migrate up

./run exec supervisord -c $REPOSITORY_PATH/supervisord.conf

exit 0
